spring:
  kafka:
    bootstrap-servers: 130.193.56.118:9092
    groupId: "report"
    consumer:
      auto-offset-reset: earliest
      portion-topic: "letters"
    producer:
      portion-topic: "portion"
  datasource:
    url: jdbc:postgresql://130.193.56.118:5432/pejt_portions
    username: postgres
    password: mcpmwC8gGwVKr4Q9xCKZEzEgS
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
server:
  port: 8088
