spring:
  kafka:
    bootstrap-servers: 130.193.56.118:9092
    consumer:
      group-id: "shipment"
      auto-offset-reset: earliest
      topic: "letters"
    producer:
      topic: "portions"
  datasource:
    url: jdbc:postgresql://192.198.1.1:5432/pejt_portions
    username: postgres
    password: 1234
interceptor:
  kafka:
    bootstrap: 192.168.1.1:9092
    topic: "url"
server:
  port: 8088