spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/portions
    username: postgres
    password: mcpmwC8gGwVKr4Q9xCKZEzEgS
  kafka:
    bootstrap-servers: localhost:9092
    groupId: "shipment"
    consumer:
      auto-offset-reset: earliest
      portion-topic: "letters"
    producer:
      portion-topic: "portions"
  jpa:
    show-sql: true
interceptor:
  kafka:
    bootstrap: localhost:9092
    topic: "url"
server:
  port: 8088