spring:
  kafka:
    bootstrap-servers: localhost:9092
    groupId: "shipment"
    consumer:
      auto-offset-reset: earliest
      portion-topic: "letters"
    producer:
      portion-topic: "portion"
  datasource:
    url: jdbc:postgresql://localhost:5434/portions
    username: postgres
    password: mcpmwC8gGwVKr4Q9xCKZEzEgS
  jpa:
    show-sql: true