spring:
  datasource:
    url: jdbc:postgresql://130.193.56.118:5432/pejt_portions
    username: postgres
    password: mcpmwC8gGwVKr4Q9xCKZEzEgS
  kafka:
    bootstrap-servers: 130.193.56.118:9092
    groupId: "shipment"
    consumer:
      auto-offset-reset: earliest
      portion-topic: "letters"
    producer:
      portion-topic: "portion"
